### ISSUE TITLE
Código -  Não foi criado uma classe de validação para o professor SEVERIDADE: Média

### ISSUE THREAD

**Issue by vafavorito** [Jovenasso/SistemaJudocas2022#19]
Não foi criada a validação para o professor:

![image](https://user-images.githubusercontent.com/80860589/204031347-652c1776-f75c-4523-8d05-558ef7c96f93.png)

**Comment by Jovenasso** [comment]
Classe de validação para professor criada.

[commit Validator Professor](https://github.com/Jovenasso/SistemaJudocas2022/commit/b58cd75c87c52ab51996029077040aca73aacdba)
